#------------------------------------------------
#-- individual configuration of the plugin manager
#--
#-- microelly 2015
#--
#-- GNU Lesser General Public License (LGPL)
#-------------------------------------------------

# here you can configure your own package list, toolbars and tabs


#
# plugins section
#
# still not active
# examples come soon
#

#plugins: 
#  #<<: *plugins
#  fasteners: *fasteners
#  styles: *styles
#


#
# toolbars section 
#
# 1. subkey = Name of the Workbench
# 2. subkey = Name of the Toolbar
# 3. subkey = Name of the Item
# 4. subkeys: Confogiuration of the Item (Icon, Command, ...)
#

toolbars:
  #<<: *toolbars
  FastenersWorkbench:
    my ToolBar:
      FEM: *FEM
    my other Toolbar:
      PCB: *pcb
      Cura Engine: *cura
      Hyperbola: *Hyperbola
  PartWorkbench:
     my PartTools:
      Move:  
          icon: icons:Draft_Move.svg 
          exec: import DraftTools;DraftTools.Move().Activated()
      mars:
          icon:  /usr/lib/freecad/Mod/plugins/icons/sun.png
          exec: fn="AppHomePath/Mod/plugins/status.py";d={};exec(open(fn).read() + "\nsun()\n",d,d)
      sun:
          icon:  /usr/lib/freecad/Mod/plugins/icons/mars.png
          exec: fn="AppHomePath/Mod/plugins/status.py";d={};exec(open(fn).read() + "\nmars()\n",d,d)


#
# tabs section
#
# 1. subkey = Name of the Tab
# 2. subkey = Name of the Item
# 3. subkeys: Confogiuration of the Item (Icon, Command, ...)
#

tabs:
   <<: *tabs
   
#-----------------------------

   Z Current:
      033 Peel the Egg: *peg
      032 Unfold Paper Model: *unfold
      0321 Align to xy Plane: *2xy
      
      0391 Hyperbola: *Hyperbola
      0392 GeodesicDome: *GeoDo
      0394 Box:
          icon: /usr/lib/freecad/Mod/plugins/icons/part.png 
          exec: |
            import Part
            App.ActiveDocument.addObject("Part::Box","Box")
            App.ActiveDocument.ActiveObject.Label = "Cube"
            App.activeDocument().recompute()


      043 Part WB: *Part
      042 Draft WB: *Draft
      044 PartDesign WB: *PartDesign
      
      0531 Object Design Workflow Tree: *ObjTree
      0532 Workfeature Macro: *wofe

      0631 Move (g): &g 
          icon: icons:Draft_Move.svg 
          exec: import DraftTools;DraftTools.Move().Activated()
      0632 Rotate (r):  &r
          icon: icons:Draft_Rotate.svg 
          exec: import DraftTools;DraftTools.Rotate().Activated()


      09 Reload PluginManager:
          exec: PluginManager.reload()
          icon:  /usr/lib/freecad/Mod/plugins/icons/mars.png

      0811 macro manager:
        man: http://forum.freecadweb.org/viewtopic.php?f=21&t=10905&start=20    
        exec: fn="AppHomePath/Mod/plugins/macromanager.py";d={};exec(open(fn).read(),d,d)
        icon: AppHomePath/Mod/Animation/icons/manager.png

#------------------------------

   040 Workbenches:
      32 Sheetmetal WB: *sheetmetal
      31 Fasteners WB: *fasteners
   050 Eventfilter:   
      012 Start Eventfilter:
          icon: /usr/lib/freecad/Mod/plugins/icons/macro-execute.png
          exec: import eventfilter;reload(eventfilter);eventfilter.start()
      0121 Stop Eventfilter:
          icon: /usr/lib/freecad/Mod/plugins/icons/macro-stop.png
          exec: import eventfilter;reload(eventfilter);eventfilter.stop()

   010 Examples:
      Reload PluginManager:
        exec: PluginManager.reload()
        icon:  /usr/lib/freecad/Mod/plugins/icons/mars.png
      School WB:
        exec: import FreeCAD;FreeCAD.Console.PrintWarning("I'm the School workbench!")
      Runextern:
        exec: runextern("/usr/bin/eog","/home/thomas/Bilder/bn_630.png")
      Dummy Macro: 
        exec: import FreeCAD;FreeCAD.Console.PrintWarning("Nothing to do!")
        icon:  AppHomePath/Mod/plugins/icons/master.png
        man: http://www.freecadweb.org
        info: A simple template 
      Greeting Macro : 
        exec: FreeCAD.Console.PrintWarning("Hello World!")
        icon:  AppHomePath/Mod/plugins/icons/sun.png
        man: http://www.freecadweb.org
      My Test Macro: *Mymacro


#-------------------------------------------------

   001 Macros :
    info: |
      This is my test tab. Here I change and examine whatever I want
      You can change it over Menu:  
      Tools -> Edit Parametrs -> PluginTabIndex ... Change Value 
      (10 means Your(my) Favorite (will be configurable for you next), 
      2 means CAD)
      In  _| MY TEST |_  I have the news/objects 
      under development always on top of the list.
    Foto: *Foto
    91 Rectellipse: *Rectellipse
    92 GeodesicDome: *GeoDo
    93 HalfHull: *Hahu

#-----------------------------------------------------
   002 FreeCAD Macros:
    94 MakeCircle3Points:
       exec: fn="AppHomePath/Mod/plugins/FreeCAD-macros/ObjectCreation/MakeCircle3Points.FCMacro";exec open(fn).read()
       icon: AppHomePath/Mod/plugins/icons/circle-3points.png
    95 DraftCircle3Points:
       exec: fn="AppHomePath/Mod/plugins/FreeCAD-macros/ObjectCreation/Draft_Circle_3_Points.FCMacro";exec open(fn).read()
       icon: AppHomePath/Mod/plugins/icons/circle-3points.png
    96 DraftCircle3PointsImproved:
       exec: fn="AppHomePath/Mod/plugins/FreeCAD-macros/ObjectCreation/Draft_Circle_3_Points_improved.FCMacro";exec open(fn).read()
       icon: AppHomePath/Mod/plugins/icons/circle-3points.png
    911 Ellipse-Center+2Points:
       exec: fn="AppHomePath/Mod/plugins/FreeCAD-macros/ObjectCreation/Ellipse-Center+2Points.FCMacro";exec open(fn).read()
       icon: AppHomePath/Mod/plugins/icons/ellipse-center+2points.png
    921 Airfoil_Import_and_Scale:
       exec: fn="AppHomePath/Mod/plugins/FreeCAD-macros/ObjectCreation/Airfoil_Import_and_Scale.FCMacro";exec open(fn).read();1+1
       icon: AppHomePath/Mod/plugins/icons/airfoil.png
    1216 Contextmenu by Gui.Selection:
       exec: fn="AppHomePath/Mod/plugins/selectiontoolbar.py";exec open(fn).read()
       icon: AppHomePath/Mod/plugins/icons/robot.png
#--------------------------------------------------------
   003 Psicofil Macros:
    001 AnimatedConstrain:
      exec: fn="AppHomePath/Mod/plugins/psicofil-macros/Macros/AnimatedConstrain.FCMacro";d={};exec("import FreeCAD;App=FreeCAD;\n" + open(fn).read(),d,d)
      man: https://github.com/psicofil/Macros_FreeCAD/blob/master/README.md
    002 GMSHMesh:
      exec: fn="AppHomePath/Mod/plugins/psicofil-macros/Macros/GMSHMesh.FCMacro";d={};exec("import FreeCAD;App=FreeCAD;\n" + open(fn).read(),d,d)
      man: https://github.com/psicofil/Macros_FreeCAD/blob/master/README.md
    003 ParametricCurve:
      exec: fn="AppHomePath/Mod/plugins/psicofil-macros/Macros/ParametricCurve.FCMacro";d={};exec("import FreeCAD,FreeCADGui;App=FreeCAD;\n" + open(fn).read(),d,d)
      man: https://github.com/psicofil/Macros_FreeCAD/blob/master/README.md
    004 RenderPovray:
      exec: fn="AppHomePath/Mod/plugins/psicofil-macros/Macros/RenderPovray.FCMacro";d={};exec("import FreeCAD,FreeCADGui;App=FreeCAD;\n" + open(fn).read(),d,d)
      man: https://github.com/psicofil/Macros_FreeCAD/blob/master/README.md
#-----------------------------------------------------
   004 Export to Apps:
    31 Export for Kerkythea: *kerkythea
    32 Kerkythea Renderer: 
        exec: import os;os.system("AppHomePath/Mod/plugins/Kerkythea2008/Kerkythea &")
        man: http://www.kerkythea.net/cms/
    41 ExportFem: *ExportFem
    42 Paraview:
          exec: runextern("/usr/lib/paraview/bin/paraview","/home/thomas/Bilder/bn_630.png")
    90 Reload PluginManager:
        exec: PluginManager.reload()

#-----------------------------------------------------

   050 Selection Gate:
      
      0011 Selection Gate Vertex: &sgvertex
          exec: import selectiongates;reload(selectiongates);selectiongates.vselect()
          log: 0
      0012 Selection Gate Edge: &sgedge
          exec: import selectiongates;reload(selectiongates);selectiongates.eselect()
          log: 0
      0013 Selection Gate Face: &sgface
          exec: import selectiongates;reload(selectiongates);selectiongates.fselect()
          log: 0
      0017 Reset Selection Gate: &sgclear
          exec: import selectiongates;reload(selectiongates);selectiongates.clear()
          log: 0
      01 Start Key Eventfilter:
          icon: /usr/lib/freecad/Mod/plugins/icons/macro-execute.png
          exec: import keyfilter;reload(keyfilter);keyfilter.start()
      011 Stop Key Eventfilter:
          icon: /usr/lib/freecad/Mod/plugins/icons/macro-stop.png
          exec: import keyfilter;reload(keyfilter);keyfilter.stop()
          
#---------------------------------------------------
          

   051 ViewPoint Managment:
   
      001 FCCamera: *Camera
      001 Rotate View:  *RotateView
      001 Rotate View Absolute:  *RotateViewAbsolute

      01 Start Key Eventfilter:
          icon: /usr/lib/freecad/Mod/plugins/icons/macro-execute.png
          exec: import keyfilter;reload(keyfilter);keyfilter.start()
      011 Stop Key Eventfilter:
          icon: /usr/lib/freecad/Mod/plugins/icons/macro-stop.png
          exec: import keyfilter;reload(keyfilter);keyfilter.stop()
     
      09 Reload PluginManager:
          exec: PluginManager.reload()
          icon:  /usr/lib/freecad/Mod/plugins/icons/mars.png


###########################################################################

# key actions for eventserver tests          
keys:
  global:
    g: *g
    
    r: *r
    
    F2: 
      exec: dlge("das ist Funktionstaste zwei")
    F3: 
      exec: dlgi("das ist \nFunktionstaste\ndrei")
    x:
      exec: runextern("/usr/bin/eog","/home/microelly2/Bilder/bn_630.png")     
    s:
      exec: import FreeCAD;FreeCAD.Console.PrintWarning("I'm the School workbench!")





  keyserver: # mouse context sensitive key actions 


     QDockWidget:WorkFeatures: &wofi

         G: *g
         R: *r
         /: *sgclear

         7: *sgvertex
         CTRL+7: *sgvertex

         8: *sgedge
         CTRL+8: *sgedge

         9: *sgface
         CTRL+9: *sgface

         B +:  Object Base -> Axes
             
         # circle
         C C: 
              c: Circle(s) Center
              exec: import WorkFeature;WorkFeature.plot_centerCirclePoint()
         # face edge
         F C: 
              c: Face(s) center  
              exec: import WorkFeature;WorkFeature.plot_centerFacePoint()
         # objects
         J C: 
              c: Object(s) Center
              exec: import WorkFeature;WorkFeature.plot_centerObjectPoint()
         J Shift+*: Object(s) Axis

         # line axis edge
         E E:
              comment: Edge(s) Extrema
              exec: import WorkFeature;WorkFeature.plot_extremaLinePoint()
         E C:
              comment: Edge(s) Center
              exec: import WorkFeature;WorkFeature.plot_centerLinePoint()
         E F V:
                 c:   Edge Face -> Point
                 exec: import WorkFeature;WorkFeature.plot_lineFacePoint()
         #vertexes points
         V C: 
              c: Vertexcloud Center
              exec:  import WorkFeature;WorkFeature.plot_centerObjectPoint()
         V F V:   
                c: Points Faces -> Points
                exec: import WorkFeature;WorkFeature.plot_pointFacePoint()
         V E V:   
                c: Points Lines -> Points
                exec: import WorkFeature;WorkFeature.plot_pointLinePoint()
            
         
         # specials
         SHIFT+*:   
           c: Origin 
           exec: import WorkFeature;WorkFeature.plot_originObject()
          
#-------------------------------------------------------------------        
         E E I: Line line ->Point intersection
         C V:  Click creates Vertex
         B V: objects Base Point
         W Q C: wire  zahl 12345 -> cutpoints
         V S: Points to Scetch
         
         # axis 1
         V V X: two points Axis
         Y X: Cylinder Axis
         F X: Plane Axis
         F N: Face Normal 
          
         V E X: Point Line -> Axis
         E V X: Axis Point -> Axis
         E E X: Line Line -> Axis
         F E V X: Plane Axis Point -> Axis
         
         # axis 2
         F E X: 
            c: Planes Axes -> Axes
            exec: FreeCAD.Console.PrintWarning("\nI'm the A Key!\n\n")
         F F X: Plane Plane -> Axis 
         E V D X:  Axis Point Distancef
         C X: Click Click -> Axis
         E S:  Axis to Sketch
         
         # circle
         N V C: direction point -> circle
         N V R: direction radiuspoint -> circle
         V V V C: 3 points -> circle
         A C: arc cuts
         V V E: 3 vertex -> ellipse
         C S: circle to sketch
         
         #plane
         V F A: 3 vertex -> plane
         V E F: vertex edge -> plane
         V N F: vertex normal -> plane
         V L F: vertex plane -> parallel plane
         E N F: edge plane -> normal plane
         F L: plane -> parallel plane
         F T: Face Tangent
         C F: click Face
         F W: enlarge Plane
         J +: 
            c: Objects center planes
            exec: import WorkFeature;WorkFeature.plot_centerObjectPlanes()
            
         #object
         J B:
            c: Bounding Box
            exec: import WorkFeature;WorkFeature.plot_boundingBoxes()
         
         J J B:
            c: Bounding Box multi
            exec: import WorkFeature;WorkFeature.plot_boundingBox()
            
         V A: align view
         V C: view camera
         
         Q L: check parallel
         Q R: check perpendicular







# Short keys for View Management


         # Rotate View Relative
         CTRL+1:
            pre: *RotateView
            exec: FreeCAD.ViewMgrRel.rotY(5)
         CTRL+2:
            pre: *RotateView
            exec: FreeCAD.ViewMgrRel.rotZ(5)
         CTRL+3:
            pre: *RotateView
            exec: FreeCAD.ViewMgrRel.rotX(5)
         CTRL+4:
            pre: *RotateView
            exec: FreeCAD.ViewMgrRel.rotY(-5)
         CTRL+5:
            pre: *RotateView
            exec: FreeCAD.ViewMgrRel.rotZ(-5)
         CTRL+6:
            pre: *RotateView
            exec: FreeCAD.ViewMgrRel.rotX(-5)
         
         # Rotate View Absolute
         ALT+2: 
           say: alt 2
           pre: *RotateViewAbsolute
           exec: FreeCAD.ViewMgr.rotZ(5)
         ALT+3:
           pre: *RotateViewAbsolute
           exec: FreeCAD.ViewMgr.rotY(5)
         ALT+5: 
           pre: *RotateViewAbsolute
           say: alt 5
           exec: FreeCAD.ViewMgr.rotZ(-5)
         ALT+6:
           pre: *RotateViewAbsolute
           exec: FreeCAD.ViewMgr.rotY(-5)
           
           
         # helpers for tests
         CTRL+0: 
           #pre: *c1
           exec: |
             FreeCAD.ViewMgrRel=None
             FreeCAD.ViewMgr=None
           #post: *b1




          
     
     QMdiArea: *wofi  
     QMainWindow: *wofi  
     
     
